In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/play-tennis/play_tennis.csv

In [2]:
data = pd.read_csv('/kaggle/input/play-tennis/play_tennis.csv')
data.head()
data.drop(columns=['day'] , inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
#Problem 1

#Outlook = sunny , temp = hot , humidity = high , wind = weak
#Play or No Play;

In [5]:
#solution ->via NaiveBayes ->we can say
#P(yes| sunny,hot,high,weak) = P(sunny|yes)*P(hot|yes)*P(high|yes)*P(weak|yes)*P(yes)
#P(No| sunny,hot,high,weak) = P(sunny|No)*P(hot|No)*P(high|No)*P(weak|No)*P(No)

#compare and decide using Maximum a Postriori rule ->in NaiveBayes

- What if the probelm changes

In [6]:
#Problem 2

#Outlook = Overcast , temp = cold , humidity = low , wind = weak
#Play or No Play;

In [7]:
#solution ->via NaiveBayes ->we can say
#P(yes| Overcast,cold,low,weak) = P(Overcast|yes)*P(cold|yes)*P(low|yes)*P(weak|yes)*P(yes)
#P(No| Overcast,cold,low,weak) = P(Overcast|No)*P(cold|No)*P(low|No)*P(weak|No)*P(No)

#compare and decide using Maximum a Postriori rule ->in NaiveBayes

- We know any MLalgo works in 2stages

In [8]:
#Training

#Lookup Table(Dictionary) ->all possible probabilities(values taken and use)
 
#Testing

- Let's make a LookupTable

In [9]:
#P(yes)
#P(No)

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
Py = 9/14
Pn = 5/14

In [12]:
print(Py)
print(Pn)

0.6428571428571429
0.35714285714285715

In [13]:
#OutLook
#rather than doing it manually , we can make a crosstab for it:
pd.crosstab(data['outlook'] , data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [15]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [16]:
#now crosstab for another columns:
#temp ->
pd.crosstab(data['temp'] , data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [17]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [18]:
#humidity
pd.crosstab(data['humidity'] , data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [20]:
#wind
pd.crosstab(data['wind'] , data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [21]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [22]:
#Now we have our LookUpTable

#What's the answer of this ->
#Outlook = sunny , temp = hot , humidity = high , wind = weak
#Play or No Play;

#based on this condition ->prob(Yes)
Pyes = Py * Psy * PHotYes * PHighYes * PWeakYes
print(Pyes)
#based on this condition ->prob(No)
Pno = Pn * Psn * PHotNo * PHighNo * PWeakNo
print(Pno)

0.007054673721340388
0.02742857142857143

In [23]:
if(Pyes>Pno):
    print("Game Play")
else:
    print("Game Not Play")

Game Not Play